services:
  app:
    build:
      context: .
    container_name: yorkgpt-server
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    tty: true
    environment:
      - OLLAMA_MODELS=../../root/.ollama/models
      - OLLAMA_HOST=http://0.0.0.0:11434
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_INTEL_GPU=true
      - OLLAMA_MAX_LOADED_MODELS=1
      - EMBEDDING_API_KEY_FILE=/run/secrets/embedding_api_key
    privileged: true
    restart: unless-stopped
    secrets:
      - embedding_api_key
    depends_on:
      - vectordb
  
  vectordb:
    image: pgvector/pgvector:pg16
    container_name: vector-db
    ports:
      - 5432:5432
    restart: unless-stopped
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=rag
      - POSTGRES_PASSWORD=langchain
      - POSTGRES_HOST_AUTH_METHOD=trust
  
secrets:
  embedding_api_key:
    file: ./embedding_api_key.txt
